title: Home Assistant - Raspberry Pi 4 B, 4 GB Новый основной сервер
views:
  - !include lovelace/01_system.yaml
  - !include lovelace/02_control.yaml
  - !include lovelace/05_lr_climate.yaml
  - !include lovelace/06_bt_control.yaml
  - !include lovelace/07_dd_climate.yaml
  - !include lovelace/07_dd_control.yaml
  - !include lovelace/08_da_climate.yaml
  - !include lovelace/08_da_control.yaml